### ISSUE TITLE
`save`: verify if the file exists

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/anime-list#2]
If the file already exists open it with write permissions (to overwrite)
If the file does not exists open it with append permissions (to append)

**Comment by suhel-45** [comment]
Hey  I am Suhel 
I am beginner in Git Hub help me.If you do so I will be Happy
  I want to  contribute in this repository .

**Comment by kauefraga** [comment]
Oh, sure. Do you have some experience with Python or Git?
This issue is about [the `save` command](https://github.com/kauefraga/anime-list/blob/main/src/commands/save.py). This command query all animes from the database and then save it into a .csv file.
The code is appending all animes every time. If you try twice the file will have "two" tables in it (replicated).
We need to adjust this to "append" if the file does not exists and overwrite if the file exists.

**Comment by kauefraga** [comment]
This happens if you run twice. There are two tables.
```csv
-->>Title, URL, Created At
Mirai Nikki, https://betteranime.net/anime/legendado/mirai-nikki, 2023-01-04 22:33:16.805562
Beast Tamer, https://betteranime.net/anime/legendado/yuusha-party-wo-tsuihou-sareta-beast-tamer-saikyoushu-no-nekomimi-shoujo-to-deau, 2023-01-04 22:33:16.873342
.............
-->>Title, URL, Created At
Mirai Nikki, https://betteranime.net/anime/legendado/mirai-nikki, 2023-01-04 22:33:16.805562
Beast Tamer, https://betteranime.net/anime/legendado/yuusha-party-wo-tsuihou-sareta-beast-tamer-saikyoushu-no-nekomimi-shoujo-to-deau, 2023-01-04 22:33:16.873342
.............
```

**Comment by suhel-45** [comment]
Currently I am pursuing engineering in computer science. I have  knowledge
in python.
I have basic knowledge of Git

**Comment by kauefraga** [comment]
That's awesome! The [README](https://github.com/kauefraga/anime-list/blob/main/README.md) has some information about the project, read it. Then clone it (`git clone https://github.com/kauefraga/anime-list.git`), code something and try to open a pull request closing this issue #2. Or just code something and send me here in the issue.
Let me know if you need some help.

**Comment by suhel-45** [comment]
Hii
I need your help . I am unable to run the project in my editor
I tried with vscode and pycharm
Please help me🙏

**Comment by kauefraga** [comment]
Hiii! Thank you for your patience. Do you still need help?
I use vscode with some extensions and it is good enough to code with Python, i recommend!
When you install [vscode](https://code.visualstudio.com) you have the `code` command at terminal.
Try to run it in the project directory:  
```bash
code <project-dir>
# or
code . # dot means actual directory
```

**Comment by suhel-45** [comment]
Hii ,I am glad that you replied I facing this problem (see in the terminal)   Sent from Mail for Windows From: Kauê Fraga RodriguesSent: 11 January 2023 05:34To: kauefraga/anime-listCc: suhel-45; CommentSubject: Re: [kauefraga/anime-list] `save`: verify if the file exists (Issue #2) Hiii! Thank you for your patience. Do you still need help?I use vscode with some extensions and it is so good enough to code with Python, i recommend!When you install vscode you have the code command at terminal.Try to run it in the project directory:code <project-dir># orcode . # dot means actual directory—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by kauefraga** [comment]
I can't figure out which bug it is. Try to reinstall, is may work.

**Comment by suhel-45** [comment]
Why u said like that
